version: "3"

services:

    php-fpm:
        build: install/php-fpm
        container_name: php-fpm
        ports:
            - 9000:9000
        volumes:
            - ${DOCUMENT_ROOT-./www}:/var/www/html/
        links:
            - mysql

    nginx:
        build: install/nginx
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${DOCUMENT_ROOT-./www}:/var/www/html/
        links:
            - php-fpm

    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - 3306:3306
              # restart: always
        environment:
            MYSQL_DATABASE: resadb
            MYSQL_USER: resa
            MYSQL_PASSWORD: resa
            MYSQL_ROOT_PASSWORD: toortoor
        volumes:
            - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql        
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8080:80
        volumes: 
            - /sessions

#    redis:
#        container_name: redis
#        image: redis:latest
#        ports:
#            - "6379:6379"

#    ftpd_server:
#        image: stilliard/pure-ftpd:hardened
#        container_name: ftpd_server
#        ports:
#            - "21:21"
#            - "30000-30009:30000-30009"
#        volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
#            - "${DOCUMENT_ROOT-./www}:/home/username/"
#            #- "/folder_on_disk/data:/home/username/"
#            #- "/folder_on_disk/passwd:/etc/pure-ftpd/passwd"
#            # uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#            #- "/folder_on_disk/ssl:/etc/ssl/private/"
#        environment:
#            PUBLICHOST: "0.0.0.0"
#            FTP_USER_NAME: username
#            FTP_USER_PASS: mypass
#            FTP_USER_HOME: /home/username
#            # also for ssl/tls:
#            # ADDED_FLAGS: "--tls=2"
#        restart: always

