#!/bin/bash

args="$@"
command="php artisan $args"
echo "$command"
docker exec -it php-fpm bash -c "/bin/bash -c \"$command\""
##docker exec -it laravel-app bash -c "sudo -u alejandro /bin/bash -c \"$command\""
